### ISSUE TITLE
.babelrc 热替换问题

### ISSUE THREAD

**Issue by souse** [fireyy/react-antd-admin#8]
之前 clone了一个版本，.babelrc 有个配置

"env": {
    "development": {
      "presets": ["react-hmre"]
    }
  }

现在 .babelrc 把该配置去掉了，我在修改组件之后并没有更新。
并且会报如下提示：

process-update.js:81[HMR] The following modules couldn't be hot updated: (Full reload needed)
This is usually because the modules which have changed (and their parents) do not know how to hot reload themselves. See http://webpack.github.io/docs/hot-module-replacement-with-webpack.html for more details.

如果带上env配置， prod 打包以后 运行就会报 react module错误。

不知道该如何处理，希望能给一个方案。

**Comment by fireyy** [comment]
之前用的 hot reload 模块不更新了，最近我会更新一个版本，用新的模块



On Wed, Dec 14, 2016 at 9:26 PM, zhangping2014 <notifications@github.com> wrote:
之前 clone了一个版本，.babelrc 有个配置

"env": {
"development": {
"presets": ["react-hmre"]
}
}

现在 .babelrc 把该配置去掉了，我在修改组件之后并没有更新。
并且会报如下提示：

process-update.js:81[HMR] The following modules couldn't be hot updated: (Full reload needed)
This is usually because the modules which have changed (and their parents) do not know how to hot reload themselves. See http://webpack.github.io/docs/hot-module-replacement-with-webpack.html [http://webpack.github.io/docs/hot-module-replacement-with-webpack.html] for more details.

如果带上env配置， prod 打包以后 运行就会报 react module错误。

不知道该如何处理，希望能给一个方案。

**Comment by souse** [comment]
如果更新好了 麻烦在问题下面回一下。 @fireyy

**Comment by fireyy** [comment]
done b899eca50f70ffa5cb1c6ec51a878474e51b6352

**Comment by souse** [comment]
谢谢 @fireyy
